/* pll_wrap.v – PLL wrapper for the Clash-generated CPURiscV top entity.
 *
 * Takes the Tang Nano 20K's 27 MHz oscillator, multiplies it to 54 MHz
 * using the on-chip rPLL, and feeds it into the Clash-generated `top`
 * module.  The wrapper exposes the same external ports as `top` so the
 * existing .cst pin-constraint file works unchanged.
 *
 * Gowin rPLL (Apycula/gowin_pack formula):
 *   FOUT = FCLKIN × (FBDIV_SEL + 1) / (IDIV_SEL + 1)
 *        = 27    × 2               / 1               = 54 MHz
 *   VCO  = FOUT × ODIV_SEL   (must be 500–1250 MHz; valid: 2/4/8/16/32/48/64/80/96/112/128)
 *        = 54   × 16                                 = 864 MHz ✓
 *   (ODIV_SEL tunes the VCO frequency; it does NOT divide the output)
 *
 * Synthesis top module: pll_top  (set in config.lushay.json)
 */
`default_nettype none

module pll_top (
    input  wire        clk,          // 27 MHz from board oscillator (pin 4)
    input  wire        uart_rx_pin,
    output wire        uart_tx_pin,
    output wire [5:0]  led
);

    // ── PLL: 27 MHz → 54 MHz ────────────────────────────────────────────
    wire clk_54;
    wire pll_lock;

    rPLL #(
        .FCLKIN     ("27"),   // input frequency string (MHz)
        .IDIV_SEL   (0),      // IDIV  = IDIV_SEL  + 1 = 1
        .FBDIV_SEL  (1),      // FBDIV = FBDIV_SEL + 1 = 2  → FOUT = 27*2 = 54 MHz
        .ODIV_SEL   (16),     // VCO   = FOUT * ODIV_SEL    = 54*16 = 864 MHz (valid, in range)
        .PSDA_SEL   ("0000"),
        .DYN_DA_EN  ("false"),
        .DUTYDA_SEL ("1000"),
        .CLKOUT_FT_DIR (1'b1)
    ) pll_inst (
        .CLKIN   (clk),
        .CLKOUT  (clk_54),
        .LOCK    (pll_lock),
        // unused / tied-off ports
        .CLKFB   (1'b0),
        .FBDSEL  (6'd0),
        .IDSEL   (6'd0),
        .ODSEL   (6'd0),
        .DUTYDA  (4'd0),
        .PSDA    (4'd0),
        .FDLY    (4'd0),
        .RESET   (1'b0),
        .RESET_P (1'b0)
    );

    // ── Clash-generated CPU core ─────────────────────────────────────────
    // The core uses power-on register initialisation for reset; no explicit
    // rst port is generated by Clash.  The PLL lock signal is not wired to
    // a reset because the Clash domain uses initial-value-based reset that
    // is guaranteed by the FPGA fabric's power-on state.
    top cpu_core (
        .clk         (clk_54),
        .uart_rx_pin (uart_rx_pin),
        .uart_tx_pin (uart_tx_pin),
        .led         (led)
    );

endmodule
