/* pll_wrap.v – PLL wrapper for the Clash-generated CPURiscV top entity.
 *
 * Takes the Tang Nano 20K's 27 MHz oscillator, multiplies it to 78 MHz
 * (exactly 27 * 26 / 9 = 78 MHz) using the on-chip rPLL, and feeds it
 * into the Clash-generated `top` module.  The wrapper exposes the same
 * external ports as `top` so the existing .cst pin-constraint file works
 * unchanged.
 *
 * This is the highest frequency achievable while satisfying both:
 *   - PFD = FCLKIN / (IDIV+1) >= 3 MHz  (gowin_pack requirement)
 *   - VCO in valid range
 *
 * Gowin rPLL (Apycula/gowin_pack formula):
 *   FOUT = FCLKIN × (FBDIV_SEL + 1) / (IDIV_SEL + 1)
 *        = 27    × 26              / 9               = 78 MHz
 *   VCO  = FOUT × ODIV_SEL   (must be 500–1250 MHz)
 *        = 78    × 8                                  = 624 MHz ✓
 *
 * Synthesis top module: pll_top  (set in config.lushay.json)
 */
`default_nettype none

module pll_top (
    input  wire        clk,          // 27 MHz from board oscillator (pin 4)
    input  wire        uart_rx_pin,
    output wire        uart_tx_pin,
    output wire [5:0]  led
);

    // ── PLL: 27 MHz → 78 MHz ──────────────────────────────────────────────────────
    wire clk_81;
    wire pll_lock;

    rPLL #(
        .FCLKIN     ("27"),   // input frequency string (MHz)
        .IDIV_SEL   (8),      // IDIV  = IDIV_SEL  + 1 = 9
        .FBDIV_SEL  (25),     // FBDIV = FBDIV_SEL + 1 = 26 → FOUT = 27*26/9 = 78 MHz
        .ODIV_SEL   (8),      // VCO   = FOUT * ODIV_SEL    = 78*8 = 624 MHz (valid, in range)
        .PSDA_SEL   ("0000"),
        .DYN_DA_EN  ("false"),
        .DUTYDA_SEL ("1000"),
        .CLKOUT_FT_DIR (1'b1)
    ) pll_inst (
        .CLKIN   (clk),
        .CLKOUT  (clk_81),
        .LOCK    (pll_lock),
        // unused / tied-off ports
        .CLKFB   (1'b0),
        .FBDSEL  (6'd0),
        .IDSEL   (6'd0),
        .ODSEL   (6'd0),
        .DUTYDA  (4'd0),
        .PSDA    (4'd0),
        .FDLY    (4'd0),
        .RESET   (1'b0),
        .RESET_P (1'b0)
    );

    // ── Clash-generated CPU core ─────────────────────────────────────────
    // The core uses power-on register initialisation for reset; no explicit
    // rst port is generated by Clash.  The PLL lock signal is not wired to
    // a reset because the Clash domain uses initial-value-based reset that
    // is guaranteed by the FPGA fabric's power-on state.
    top cpu_core (
        .clk         (clk_81),
        .uart_rx_pin (uart_rx_pin),
        .uart_tx_pin (uart_tx_pin),
        .led         (led)
    );

endmodule
