/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.1. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module top
    ( // Inputs
      input wire  clk // clock
    , input wire  uart_rx_pin

      // Outputs
    , output wire  uart_tx_pin
    , output wire [5:0] led
    );
  // src/Processor.hs:342:1-10
  wire  c$ds_app_arg;
  // src/Processor.hs:342:1-10
  reg [576:0] c$ds_app_arg_0 = {{2'd0,   12'd0,   32'b00000000000000000000000000000000,   1'b1,   8'b11111111,
  1'b0,   8'b00000000,   16'd0},   {10'd0,   {32'd0,   32'd0,   32'd0,
                                              32'd0},   1'b0,   {1'b0,   10'd0,
                                                                 32'b00000000000000000000000000000000,
                                                                 1'b0,
                                                                 10'd0},
                                    {1'b0,   10'd0,   4'b0000,   2'd0,   32'd0,
                                     32'd0,   1'b0,   10'd0},   1'b0,
                                    8'b00000000,   1'b0,   10'd0},
 {{8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,
   8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,
   8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,
   8'b00000000},   4'd0,   4'd0},   {2'd0,   9'd0,   3'd0,   8'b00000000,
                                     1'b1,   1'b1,   8'b00000000,   1'b0},
 {2'd0,   9'd0,   3'd0,   8'b00000000,   1'b1}};
  // src/Processor.hs:342:1-10
  wire  c$ds_app_arg_1;
  reg [31:0] result_0;
  // src/Processor.hs:342:1-10
  wire [41:0] a1;
  // src/Processor.hs:342:1-10
  wire [59:0] fullOut;
  wire [636:0] result_1;
  // src/Processor.hs:279:1-8
  wire [22:0] \tx' ;
  wire [135:0] c$app_arg;
  wire [135:0] c$case_alt;
  wire [127:0] c$app_arg_0;
  // src/Processor.hs:279:1-8
  wire [135:0] fifo3;
  reg  c$case_alt_0;
  // src/Processor.hs:279:1-8
  wire [15:0] runTimeout1;
  // src/Processor.hs:279:1-8
  wire [7:0] out3PendDat1;
  // src/Processor.hs:279:1-8
  wire  cpu3Rst1;
  // src/Processor.hs:279:1-8
  wire [31:0] progWordAcc1;
  // src/Processor.hs:279:1-8
  wire [11:0] progByteIdx1;
  // src/Processor.hs:279:1-8
  wire [1:0] eta1;
  // src/Processor.hs:279:1-8
  wire  out3Pending1;
  // src/Processor.hs:279:1-8
  wire [79:0] top2;
  // src/Processor.hs:279:1-8
  wire [7:0] \c$led3Latch'_case_alt ;
  // src/Processor.hs:279:1-8
  wire  wild4;
  reg [563:0] result_2;
  wire [563:0] c$case_alt_1;
  wire [79:0] c$app_arg_1;
  // src/Processor.hs:279:1-8
  wire [7:0] out3PendDat1_0;
  // src/Processor.hs:279:1-8
  wire [7:0] led3Latch1;
  // src/Processor.hs:279:1-8
  wire  cpu3Rst1_0;
  // src/Processor.hs:279:1-8
  wire [31:0] progWordAcc1_0;
  // src/Processor.hs:279:1-8
  wire [11:0] progByteIdx1_0;
  // src/Processor.hs:279:1-8
  wire [79:0] wild8;
  // src/Processor.hs:279:1-8
  wire [215:0] c$ds19_case_alt;
  // src/Processor.hs:279:1-8
  wire  wild9;
  // src/Processor.hs:279:1-8
  wire [215:0] c$ds19_case_alt_0;
  // src/Processor.hs:279:1-8
  wire [215:0] c$ds19_case_alt_1;
  wire [563:0] c$case_alt_2;
  wire [563:0] result_3;
  // src/Processor.hs:279:1-8
  wire [42:0] pgWr;
  wire [135:0] c$app_arg_2;
  wire  c$case_scrut;
  wire [31:0] c$app_arg_3;
  // src/Processor.hs:279:1-8
  wire  c$pgWr_case_scrut;
  // src/Processor.hs:279:1-8
  wire [31:0] \wordAcc' ;
  // src/Processor.hs:279:1-8
  wire signed [63:0] ds20;
  // src/Processor.hs:279:1-8
  wire signed [63:0] c$ds20_app_arg;
  // src/Processor.hs:279:1-8
  wire [11:0] bytePos;
  wire [79:0] c$app_arg_4;
  wire [79:0] c$case_alt_3;
  wire [79:0] c$case_alt_4;
  wire [135:0] c$case_alt_5;
  wire [127:0] c$app_arg_5;
  reg [7:0] c$fifoPush3Out_app_arg;
  // src/Processor.hs:279:1-8
  wire [7:0] cpuOD;
  // src/Processor.hs:279:1-8
  wire [335:0] c$ds9_case_alt;
  // src/Processor.hs:279:1-8
  wire [9:0] _brTarget;
  // src/Processor.hs:279:1-8
  wire  _brActual;
  // src/Processor.hs:279:1-8
  wire  cpuHalted;
  // src/Processor.hs:279:1-8
  wire [7:0] cpuOD_0;
  // src/Processor.hs:279:1-8
  wire  cpuOV;
  // src/Processor.hs:279:1-8
  wire [9:0] _nextPC;
  // src/Processor.hs:279:1-8
  wire [304:0] cpu1;
  wire [335:0] c$case_alt_6;
  wire [335:0] c$case_alt_7;
  // src/Processor.hs:177:1-8
  wire  brActual;
  // src/Processor.hs:177:1-8
  wire [7:0] acc_od;
  // src/Processor.hs:177:1-8
  wire  acc_ov;
  // src/Processor.hs:177:1-8
  wire  acc_halt;
  wire [91:0] result_4;
  wire [31:0] result_5;
  wire [31:0] c$case_alt_8;
  wire [31:0] c$case_alt_9;
  // src/Processor.hs:177:1-8
  wire [1:0] \rsF' ;
  wire  c$case_alt_10;
  wire  c$case_alt_11;
  wire  c$case_alt_12;
  wire  c$case_alt_13;
  wire  c$case_alt_14;
  // src/Processor.hs:177:1-8
  wire [127:0] acc_rd;
  wire [53:0] c$case_alt_15;
  // src/Processor.hs:177:1-8
  wire [9:0] c$nextPC_case_alt;
  // src/Processor.hs:177:1-8
  wire [9:0] brTarget;
  // src/Processor.hs:177:1-8
  wire [9:0] nextSeqPC;
  wire [183:0] c$tupIn;
  // src/Processor.hs:177:1-8
  wire [159:0] c$ds10_case_alt;
  reg  result_6;
  // src/Processor.hs:177:1-8
  wire signed [63:0] \b# ;
  // src/Processor.hs:177:1-8
  wire signed [63:0] \a# ;
  // src/Processor.hs:177:1-8
  wire [8:0] ds20_0;
  // src/Processor.hs:177:1-8
  wire [9:0] c$ds10_case_alt_0;
  // src/Processor.hs:177:1-8
  wire [9:0] brTg;
  // src/Processor.hs:177:1-8
  wire  wild7;
  // src/Processor.hs:177:1-8
  wire [10:0] ds19;
  // src/Processor.hs:177:1-8
  wire [10:0] c$ds19_case_alt_2;
  // src/Processor.hs:177:1-8
  wire [9:0] c$ds19_app_arg;
  // src/Processor.hs:177:1-8
  wire  c$ds19_app_arg_0;
  // src/Processor.hs:177:1-8
  wire [10:0] c$ds19_case_alt_3;
  // src/Processor.hs:177:1-8
  wire [9:0] c$ds19_app_arg_1;
  // src/Processor.hs:177:1-8
  wire [9:0] c$ds19_case_alt_4;
  // src/Processor.hs:177:1-8
  wire  c$ds19_app_arg_2;
  wire [127:0] result_7;
  // src/Processor.hs:177:1-8
  wire [127:0] c$ds10_case_alt_1;
  // src/Processor.hs:177:1-8
  wire [127:0] c$ds10_case_alt_2;
  // src/Processor.hs:177:1-8
  wire [127:0] c$ds10_case_alt_3;
  // src/Processor.hs:177:1-8
  wire [127:0] c$ds10_case_alt_4;
  // src/Processor.hs:177:1-8
  wire [127:0] c$ds10_case_alt_5;
  // src/Processor.hs:177:1-8
  wire [127:0] c$ds10_case_alt_6;
  // src/Processor.hs:177:1-8
  wire [31:0] aluResult;
  // src/Processor.hs:177:1-8
  wire [31:0] c$aluResult_case_alt;
  // src/Processor.hs:177:1-8
  wire [31:0] c$aluResult_case_alt_0;
  // src/Processor.hs:177:1-8
  wire [31:0] c$aluResult_case_alt_1;
  // src/Processor.hs:177:1-8
  wire [31:0] c$aluResult_case_alt_2;
  // src/Processor.hs:177:1-8
  wire  c$ds10_case_scrut;
  // src/Processor.hs:177:1-8
  wire  c$ds10_case_scrut_0;
  // src/Processor.hs:177:1-8
  wire  c$ds10_case_scrut_1;
  // src/Processor.hs:177:1-8
  wire  c$ds10_case_scrut_2;
  // src/Processor.hs:177:1-8
  wire  c$ds10_case_scrut_3;
  // src/Processor.hs:177:1-8
  wire [3:0] ds12;
  // src/Processor.hs:177:1-8
  wire [31:0] ds6;
  // src/Processor.hs:177:1-8
  wire [1:0] ds4;
  wire [31:0] result_8;
  // src/Processor.hs:177:1-8
  wire [1:0] rsF;
  // src/Processor.hs:177:1-8
  wire [31:0] c$rsF_app_arg;
  // src/Processor.hs:177:1-8
  wire [31:0] instr;
  // src/Processor.hs:279:1-8
  wire  cpuEn;
  // src/Processor.hs:279:1-8
  reg  c$cpuEn_case_alt;
  // src/Processor.hs:279:1-8
  wire signed [63:0] c$cpuEn_case_scrut;
  // src/Processor.hs:279:1-8
  wire  rxVld;
  // src/Processor.hs:279:1-8
  wire [7:0] rxByte;
  // src/Processor.hs:279:1-8
  wire [32:0] \rx' ;
  wire [41:0] result_9;
  // src/Processor.hs:83:1-8
  wire [7:0] c$dataOut_case_alt;
  // src/Processor.hs:83:1-8
  wire [7:0] \shift' ;
  // src/Processor.hs:83:1-8
  wire  wild3;
  // src/Processor.hs:83:1-8
  reg [22:0] ds8;
  // src/Processor.hs:83:1-8
  wire [22:0] c$ds8_case_alt;
  // src/Processor.hs:83:1-8
  wire [22:0] c$ds8_case_alt_0;
  // src/Processor.hs:83:1-8
  wire [22:0] c$ds8_case_alt_1;
  // src/Processor.hs:83:1-8
  wire [22:0] c$ds8_case_alt_2;
  // src/Processor.hs:83:1-8
  wire  c$ds8_case_scrut;
  wire [22:0] result_10;
  // src/Processor.hs:83:1-8
  wire [7:0] shifted;
  // src/Processor.hs:83:1-8
  wire [22:0] c$ds8_case_alt_3;
  // src/Processor.hs:83:1-8
  wire [8:0] c$ds8_app_arg;
  // src/Processor.hs:83:1-8
  wire  c$ds8_case_scrut_0;
  wire [24:0] result_11;
  // src/Processor.hs:123:1-8
  wire  \pin' ;
  // src/Processor.hs:123:1-8
  reg [22:0] ds6_0;
  // src/Processor.hs:123:1-8
  wire [22:0] c$ds6_case_alt;
  // src/Processor.hs:123:1-8
  wire [22:0] c$ds6_case_alt_0;
  // src/Processor.hs:123:1-8
  wire [22:0] c$ds6_case_alt_1;
  // src/Processor.hs:123:1-8
  wire [22:0] c$ds6_case_alt_2;
  wire [22:0] result_12;
  // src/Processor.hs:123:1-8
  wire [7:0] shifted_0;
  // src/Processor.hs:123:1-8
  wire  c$ds6_app_arg;
  // src/Processor.hs:123:1-8
  wire [7:0] c$ds6_app_arg_0;
  // src/Processor.hs:123:1-8
  wire  c$ds6_case_scrut;
  // src/Processor.hs:123:1-8
  wire [8:0] c$ds6_app_arg_1;
  // src/Processor.hs:123:1-8
  wire [7:0] dat;
  // src/Processor.hs:123:1-8
  wire  send;
  // src/Processor.hs:123:1-8
  reg  busy;
  // src/Processor.hs:123:1-8
  wire signed [63:0] c$busy_case_scrut;
  wire [431:0] c$tupIn_0;
  // src/Processor.hs:279:1-8
  wire [79:0] wild5;
  // src/Processor.hs:279:1-8
  wire [15:0] runTimeout1_0;
  // src/Processor.hs:279:1-8
  wire [7:0] led3Latch1_0;
  // src/Processor.hs:279:1-8
  wire  cpu3Rst1_1;
  // src/Processor.hs:279:1-8
  wire [31:0] progWordAcc1_1;
  // src/Processor.hs:279:1-8
  wire [11:0] progByteIdx1_1;
  // src/Processor.hs:279:1-8
  wire [1:0] eta1_0;
  wire [135:0] c$case_alt_16;
  wire [127:0] c$app_arg_6;
  // src/Processor.hs:279:1-8
  wire [135:0] fifo1;
  // src/Processor.hs:279:1-8
  wire [144:0] ds7;
  // src/Processor.hs:279:1-8
  reg  c$ds7_case_alt;
  // src/Processor.hs:279:1-8
  wire signed [63:0] c$ds7_case_scrut;
  wire [143:0] c$case_alt_17;
  wire [7:0] c$app_arg_7;
  // src/Processor.hs:279:1-8
  wire [7:0] out3PendDat1_1;
  // src/Processor.hs:342:1-10
  wire [42:0] eta3;
  // src/Processor.hs:342:1-10
  wire [41:0] ds1;
  wire [9:0] c$i_103;
  wire [9:0] c$i_104;
  wire [7:0] c$bv;
  wire [3:0] c$i_108;
  wire [127:0] c$vec;
  wire [1:0] result_selection_2;
  wire [11:0] c$bv_0;
  wire [7:0] c$bv_1;
  wire [4:0] c$i_124;
  wire [3:0] c$i_132;
  wire [127:0] c$vec_0;
  wire [1:0] c$fifoPush3Out_app_arg_selection_2;
  wire [1:0] c$i_155;
  wire [31:0] c$bv_2;
  wire signed [63:0] result_selection_res;
  wire  c$dtt_rhs_3;
  wire [31:0] c$bv_3;
  wire [31:0] c$bv_4;
  wire [1:0] c$i_189;
  wire [127:0] c$vec_1;
  wire [23:0] c$bv_5;
  wire [127:0] c$vecFlat;
  wire [1:0] ds8_selection_2;
  wire [7:0] c$bv_6;
  wire [1:0] ds6_selection_2;
  wire [1:0] c$dtt_rhs_7;
  wire [3:0] c$i_242;
  wire [127:0] c$vec_2;
  wire [1:0] c$dtt_rhs_11;
  wire [3:0] c$i_245;
  wire [127:0] c$vecFlat_0;
  wire [6:0] result;

  // resetGen begin
  // pragma translate_off
  reg  rst;
  localparam reset_period = 1000000 - 10 + (1 * 370370);
  `ifndef VERILATOR
  initial begin
    #1 rst =  1 ;
    #reset_period rst =  0 ;
  end
  `else
  always begin
    // The redundant (rst | ~ rst) is needed to ensure that this is
    // calculated in every cycle by verilator. Without it, the reset will stop
    // being updated and will be stuck as asserted forever.
    rst = $c("this->reset_gen(",reset_period,",true)") & (rst | ~ rst);
  end
  `systemc_interface
  CData reset_gen(vluint32_t reset_period, bool active_high) {
    static vluint32_t to_wait = reset_period;
    static CData reset = active_high ? 1 : 0;
    static bool finished = false;

    if(!finished) {
      if(to_wait == 0) {
        reset = reset == 0 ? 1 : 0;
        finished = true;
      }
      else {
        to_wait = to_wait - 1;
      }
    }

    return reset;
  }
  `verilog
  `endif
  assign c$ds_app_arg = rst;
  // pragma translate_on
  // resetGen end

  // register begin
  always @(posedge clk or  posedge  c$ds_app_arg) begin : c$ds_app_arg_0_register
    if ( c$ds_app_arg) begin
      c$ds_app_arg_0 <= {{2'd0,   12'd0,   32'b00000000000000000000000000000000,   1'b1,   8'b11111111,
    1'b0,   8'b00000000,   16'd0},   {10'd0,   {32'd0,   32'd0,   32'd0,
                                                32'd0},   1'b0,   {1'b0,   10'd0,
                                                                   32'b00000000000000000000000000000000,
                                                                   1'b0,
                                                                   10'd0},
                                      {1'b0,   10'd0,   4'b0000,   2'd0,   32'd0,
                                       32'd0,   1'b0,   10'd0},   1'b0,
                                      8'b00000000,   1'b0,   10'd0},
   {{8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,
     8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,
     8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,
     8'b00000000},   4'd0,   4'd0},   {2'd0,   9'd0,   3'd0,   8'b00000000,
                                       1'b1,   1'b1,   8'b00000000,   1'b0},
   {2'd0,   9'd0,   3'd0,   8'b00000000,   1'b1}};
    end else begin
      c$ds_app_arg_0 <= result_1[636:60];
    end
  end
  // register end

  assign c$ds_app_arg_1 = eta3[42:42] ? 1'b1 : 1'b0;

  assign c$i_103 = fullOut[52:43];

  assign c$i_104 = ds1[41:32];

  // blockRamFile begin
  reg [31:0] RAM [0:1024-1];

  initial begin
    $readmemb("prog.hex",RAM);
  end

  always @(posedge clk) begin : top3_blockRamFile
    if (c$ds_app_arg_1) begin
      RAM[($unsigned({{(64-10) {1'b0}},c$i_104}))] <= ds1[31:0];
    end
    result_0 <= RAM[($unsigned({{(64-10) {1'b0}},c$i_103}))];
  end
  // blockRamFile end

  assign result = fullOut[59:53];

  assign a1 = eta3[41:0];

  assign fullOut = result_1[59:0];

  assign c$bv = (\c$led3Latch'_case_alt );

  assign result_1 = {{{eta1,   progByteIdx1,
                       progWordAcc1,   cpu3Rst1,
                       \c$led3Latch'_case_alt ,   out3Pending1,
                       out3PendDat1,   runTimeout1},
                      result_2[347:43],   c$app_arg,   \rx' ,
                      \tx' },   {{\tx' [0:0],   ~ (c$bv[5 : 0])},
                                 result_2[347:338],   result_2[42:0]}};

  assign \tx'  = result_11[24:2];

  assign c$app_arg = (rxVld & ((rxByte == 8'b01011000) & (c$case_alt_0 & (~ ((fifo3[7:4] + 4'd1) == fifo3[3:0]))))) ? c$case_alt : fifo3;

  assign c$case_alt = {c$app_arg_0,
                       fifo3[7:4] + 4'd1,   fifo3[3:0]};

  assign c$i_108 = fifo3[7:4];

  assign c$vec = fifo3[135:8];

  // vector replace begin
  genvar i;
  generate
  for (i=0;i<16;i=i+1) begin : vector_replace
    assign c$app_arg_0[(15-i)*8+:8] = ($unsigned({{(64-4) {1'b0}},c$i_108})) == i ? 8'b01001011 : c$vec[(15-i)*8+:8];
  end
  endgenerate
  // vector replace end

  assign fifo3 = result_2[483:348];

  always @(*) begin
    case(c$cpuEn_case_scrut)
      64'sd0 : c$case_alt_0 = 1'b1;
      default : c$case_alt_0 = 1'b0;
    endcase
  end

  assign runTimeout1 = top2[15:0];

  assign out3PendDat1 = top2[23:16];

  assign cpu3Rst1 = top2[33:33];

  assign progWordAcc1 = top2[65:34];

  assign progByteIdx1 = top2[77:66];

  assign eta1 = top2[79:78];

  assign out3Pending1 = top2[24:24];

  assign top2 = result_2[563:484];

  assign \c$led3Latch'_case_alt  = wild4 ? cpuOD : led3Latch1_0;

  assign wild4 = c$ds9_case_alt[20:20];

  assign result_selection_2 = c$tupIn_0[295:294];

  always @(*) begin
    case(result_selection_2)
      2'b00 : result_2 = {c$app_arg_4,
                          c$tupIn_0[431:296],   c$ds9_case_alt[335:31],
                          {1'b0,42'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};
      2'b01 : result_2 = c$case_alt_2;
      2'b10 : result_2 = {c$app_arg_1,
                          c$ds19_case_alt[215:80],
                          c$ds9_case_alt[335:31],
                          {1'b0,42'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};
      default : result_2 = c$case_alt_1;
    endcase
  end

  assign c$case_alt_1 = c$case_scrut ? {{2'd0,
                                         c$tupIn_0[293:282],   c$tupIn_0[281:250],
                                         c$tupIn_0[249:249],   c$tupIn_0[248:241],
                                         c$tupIn_0[240:240],   c$tupIn_0[239:232],
                                         c$tupIn_0[231:216]},   c$case_alt_5,
                                        c$ds9_case_alt[335:31],
                                        {1'b0,42'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}} : {c$tupIn_0[295:216],
                                                                                                  c$tupIn_0[431:296],
                                                                                                  c$ds9_case_alt[335:31],
                                                                                                  {1'b0,42'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};

  assign c$app_arg_1 = ((c$ds9_case_alt[11:11] | (wild8[15:0] == 16'd65535)) & (~ wild8[24:24])) ? {2'd3,
                                                                                                    progByteIdx1_0,
                                                                                                    progWordAcc1_0,
                                                                                                    cpu3Rst1_0,
                                                                                                    led3Latch1,
                                                                                                    wild8[24:24],
                                                                                                    out3PendDat1_0,
                                                                                                    wild8[15:0]} : wild8;

  assign out3PendDat1_0 = wild8[23:16];

  assign led3Latch1 = wild8[32:25];

  assign cpu3Rst1_0 = wild8[33:33];

  assign progWordAcc1_0 = wild8[65:34];

  assign progByteIdx1_0 = wild8[77:66];

  assign wild8 = c$ds19_case_alt[79:0];

  assign c$ds19_case_alt = wild9 ? c$ds19_case_alt_0 : c$ds19_case_alt_1;

  assign wild9 = c$ds9_case_alt[20:20];

  assign c$ds19_case_alt_0 = c$case_scrut ? {c$case_alt_5,
                                             {2'd2,   c$tupIn_0[293:282],
                                              c$tupIn_0[281:250],   1'b0,
                                              c$tupIn_0[248:241],   c$tupIn_0[240:240],
                                              c$tupIn_0[239:232],
                                              16'd0}} : {c$tupIn_0[431:296],   {2'd2,
                                                                                c$tupIn_0[293:282],
                                                                                c$tupIn_0[281:250],   1'b0,
                                                                                c$tupIn_0[248:241],   1'b1,   cpuOD,
                                                                                16'd0}};

  assign c$ds19_case_alt_1 = (cpuEn & (~ c$tupIn_0[240:240])) ? {c$tupIn_0[431:296],
                                                                 {2'd2,   c$tupIn_0[293:282],
                                                                  c$tupIn_0[281:250],   1'b0,
                                                                  c$tupIn_0[248:241],   c$tupIn_0[240:240],
                                                                  c$tupIn_0[239:232],
                                                                  c$tupIn_0[231:216] + 16'd1}} : {c$tupIn_0[431:296],
                                                                                                  {2'd2,
                                                                                                   c$tupIn_0[293:282],
                                                                                                   c$tupIn_0[281:250],
                                                                                                   1'b0,
                                                                                                   c$tupIn_0[248:241],
                                                                                                   c$tupIn_0[240:240],
                                                                                                   c$tupIn_0[239:232],
                                                                                                   c$tupIn_0[231:216]}};

  assign c$case_alt_2 = rxVld ? result_3 : {c$tupIn_0[295:216],
                                            c$tupIn_0[431:296],   c$ds9_case_alt[335:31],
                                            {1'b0,42'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};

  assign result_3 = (c$tupIn_0[293:282] == 12'd4095) ? {{2'd0,
                                                         12'd0,   32'b00000000000000000000000000000000,
                                                         c$tupIn_0[249:249],   c$tupIn_0[248:241],
                                                         c$tupIn_0[240:240],   c$tupIn_0[239:232],
                                                         c$tupIn_0[231:216]},   c$app_arg_2,
                                                        c$ds9_case_alt[335:31],   pgWr} : {{2'd1,
                                                                                            c$tupIn_0[293:282] + 12'd1,
                                                                                            c$app_arg_3,
                                                                                            c$tupIn_0[249:249],
                                                                                            c$tupIn_0[248:241],
                                                                                            c$tupIn_0[240:240],
                                                                                            c$tupIn_0[239:232],
                                                                                            c$tupIn_0[231:216]},
                                                                                           c$tupIn_0[431:296],
                                                                                           c$ds9_case_alt[335:31],
                                                                                           pgWr};

  assign c$bv_0 = (c$tupIn_0[293:282] / 12'd4);

  assign pgWr = c$pgWr_case_scrut ? {1'b1,{c$bv_0[0+:10],
                                           \wordAcc' }} : {1'b0,42'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c$app_arg_2 = c$case_scrut ? c$case_alt_5 : c$tupIn_0[431:296];

  assign c$case_scrut = ~ ((c$tupIn_0[303:300] + 4'd1) == c$tupIn_0[299:296]);

  assign c$app_arg_3 = c$pgWr_case_scrut ? 32'b00000000000000000000000000000000 : \wordAcc' ;

  assign c$pgWr_case_scrut = bytePos == 12'd3;

  assign c$bv_1 = (rxByte);

  assign \wordAcc'  = c$tupIn_0[281:250] | (((({{(32-8) {1'b0}},(rxByte)}) << (ds20))));

  assign ds20 = $signed(c$ds20_app_arg);

  assign c$i_124 = ((5'd3 - (bytePos[0+:5])) * 5'd8);

  assign c$ds20_app_arg = $unsigned({{(64-5) {1'b0}},c$i_124});

  assign bytePos = c$tupIn_0[293:282] % 12'd4;

  assign c$app_arg_4 = (~ rxVld) ? {2'd0,
                                    c$tupIn_0[293:282],   c$tupIn_0[281:250],
                                    1'b1,   c$tupIn_0[248:241],
                                    c$tupIn_0[240:240],   c$tupIn_0[239:232],
                                    c$tupIn_0[231:216]} : c$case_alt_3;

  assign c$case_alt_3 = (rxByte == 8'b01010000) ? {2'd1,
                                                   12'd0,   32'b00000000000000000000000000000000,
                                                   1'b1,   c$tupIn_0[248:241],
                                                   c$tupIn_0[240:240],   c$tupIn_0[239:232],
                                                   c$tupIn_0[231:216]} : c$case_alt_4;

  assign c$case_alt_4 = (rxByte == 8'b01010010) ? {2'd2,
                                                   c$tupIn_0[293:282],   c$tupIn_0[281:250],
                                                   1'b0,   c$tupIn_0[248:241],
                                                   c$tupIn_0[240:240],   c$tupIn_0[239:232],
                                                   16'd0} : {2'd0,   c$tupIn_0[293:282],
                                                             c$tupIn_0[281:250],   1'b1,
                                                             c$tupIn_0[248:241],   c$tupIn_0[240:240],
                                                             c$tupIn_0[239:232],   c$tupIn_0[231:216]};

  assign c$case_alt_5 = {c$app_arg_5,
                         c$tupIn_0[303:300] + 4'd1,
                         c$tupIn_0[299:296]};

  assign c$i_132 = c$tupIn_0[303:300];

  assign c$vec_0 = c$tupIn_0[431:304];

  // vector replace begin
  genvar i_0;
  generate
  for (i_0=0;i_0<16;i_0=i_0+1) begin : vector_replace_0
    assign c$app_arg_5[(15-i_0)*8+:8] = ($unsigned({{(64-4) {1'b0}},c$i_132})) == i_0 ? c$fifoPush3Out_app_arg : c$vec_0[(15-i_0)*8+:8];
  end
  endgenerate
  // vector replace end

  assign c$fifoPush3Out_app_arg_selection_2 = c$tupIn_0[295:294];

  always @(*) begin
    case(c$fifoPush3Out_app_arg_selection_2)
      2'b01 : c$fifoPush3Out_app_arg = 8'b01001011;
      2'b10 : c$fifoPush3Out_app_arg = cpuOD;
      default : c$fifoPush3Out_app_arg = 8'b01000100;
    endcase
  end

  assign cpuOD = c$ds9_case_alt[19:12];

  assign c$ds9_case_alt = cpu3Rst1_1 ? {{10'd0,
                                         {4 {32'd0}},   1'b0,   {1'b0,   10'd0,
                                                                 32'b00000000000000000000000000000000,   1'b0,
                                                                 10'd0},   {1'b0,   10'd0,   4'b0000,   2'd0,
                                                                            32'd0,   32'd0,   1'b0,   10'd0},   1'b0,
                                         8'b00000000,   1'b0,   10'd0},   10'd0,
                                        1'b0,   8'b00000000,   1'b0,   1'b0,
                                        10'd0} : {cpu1,   _nextPC,   cpuOV,   cpuOD_0,
                                                  cpuHalted,   _brActual,   _brTarget};

  assign _brTarget = c$case_alt_6[9:0];

  assign _brActual = c$case_alt_6[10:10];

  assign cpuHalted = c$case_alt_6[11:11];

  assign cpuOD_0 = c$case_alt_6[19:12];

  assign cpuOV = c$case_alt_6[20:20];

  assign _nextPC = c$case_alt_6[30:21];

  assign cpu1 = c$case_alt_6[335:31];

  assign c$case_alt_6 = c$ds_app_arg_0[358:358] ? {{c$ds_app_arg_0[496:487],
                                                    c$ds_app_arg_0[486:359],   1'b1,
                                                    c$ds_app_arg_0[357:304],
                                                    c$ds_app_arg_0[303:212],   1'b0,
                                                    c$ds_app_arg_0[210:203],   1'b0,
                                                    c$ds_app_arg_0[201:192]},
                                                   {c$ds_app_arg_0[496:487],   1'b0,
                                                    8'b00000000,   1'b1,   1'b0,
                                                    10'd0}} : c$case_alt_7;

  assign c$case_alt_7 = (~ cpuEn) ? {{c$ds_app_arg_0[496:487],
                                      c$ds_app_arg_0[486:359],   1'b0,
                                      c$ds_app_arg_0[357:304],
                                      c$ds_app_arg_0[303:212],   1'b0,
                                      c$ds_app_arg_0[210:203],   1'b0,
                                      c$ds_app_arg_0[201:192]},
                                     {c$ds_app_arg_0[496:487],   1'b0,
                                      8'b00000000,   1'b0,   1'b0,
                                      10'd0}} : {{c$nextPC_case_alt,   acc_rd,
                                                  acc_halt,   c$case_alt_15,   result_4,
                                                  acc_ov,   acc_od,   brActual,   brTarget},
                                                 {c$nextPC_case_alt,   acc_ov,   acc_od,
                                                  acc_halt,   brActual,   brTarget}};

  assign brActual = c$ds10_case_alt[11:11];

  assign acc_od = c$ds10_case_alt[19:12];

  assign acc_ov = c$ds10_case_alt[20:20];

  assign acc_halt = c$ds10_case_alt[21:21];

  assign result_4 = c$tupIn[183:183] ? {1'b1,
                                        c$tupIn[182:173],   c$tupIn[172:169],
                                        c$tupIn[168:167],   result_5,
                                        c$tupIn[134:103],   c$tupIn[102:102],
                                        c$tupIn[101:92]} : c$tupIn[91:0];

  assign result_5 = ((c$ds_app_arg_0[303:303] & c$case_alt_10) & (c$ds_app_arg_0[288:287] == \rsF' )) ? c$case_alt_9 : c$case_alt_8;

  // index begin
  wire [31:0] vecArray [0:4-1];
  genvar i_1;
  generate
  for (i_1=0; i_1 < 4; i_1=i_1+1) begin : mk_array
    assign vecArray[(4-1)-i_1] = acc_rd[i_1*32+:32];
  end
  endgenerate
  assign c$case_alt_8 = vecArray[($unsigned({{(64-2) {1'b0}},\rsF' }))];
  // index end

  assign c$i_155 = c$ds_app_arg_0[288:287];

  // index begin
  wire [31:0] vecArray_0 [0:4-1];
  genvar i_2;
  generate
  for (i_2=0; i_2 < 4; i_2=i_2+1) begin : mk_array_0
    assign vecArray_0[(4-1)-i_2] = acc_rd[i_2*32+:32];
  end
  endgenerate
  assign c$case_alt_9 = vecArray_0[($unsigned({{(64-2) {1'b0}},c$i_155}))];
  // index end

  assign c$bv_2 = (c$ds_app_arg_0[346:315]);

  assign \rsF'  = (c$bv_2[25 : 24]);

  assign c$case_alt_10 = (c$ds_app_arg_0[292:289] == 4'b0001) ? 1'b1 : c$case_alt_11;

  assign c$case_alt_11 = (c$ds_app_arg_0[292:289] == 4'b0010) ? 1'b1 : c$case_alt_12;

  assign c$case_alt_12 = (c$ds_app_arg_0[292:289] == 4'b0011) ? 1'b1 : c$case_alt_13;

  assign c$case_alt_13 = (c$ds_app_arg_0[292:289] == 4'b0100) ? 1'b1 : c$case_alt_14;

  assign c$case_alt_14 = (c$ds_app_arg_0[292:289] == 4'b0101) ? 1'b1 : (c$ds_app_arg_0[292:289] == 4'b0110);

  assign acc_rd = c$ds10_case_alt[159:32];

  assign c$case_alt_15 = c$ds10_case_alt[0:0] ? {1'b0,
                                                 10'd0,   32'b00000000000000000000000000000000,
                                                 1'b0,   10'd0} : {1'b1,
                                                                   c$ds_app_arg_0[496:487],   result_0,   1'b0,
                                                                   nextSeqPC};

  assign c$nextPC_case_alt = c$ds10_case_alt[0:0] ? brTarget : nextSeqPC;

  assign brTarget = c$ds10_case_alt[10:1];

  assign nextSeqPC = c$ds_app_arg_0[496:487] + 10'd1;

  assign c$tupIn = (c$ds10_case_alt[0:0] | (~ c$ds_app_arg_0[357:357])) ? {1'b0,
                                                                           10'd0,   4'b0000,   2'd0,   32'd0,   32'd0,
                                                                           1'b0,   10'd0,   {1'b0,   10'd0,   4'b0000,
                                                                                             2'd0,   32'd0,   32'd0,
                                                                                             1'b0,   10'd0}} : {1'b1,
                                                                                                                c$ds_app_arg_0[356:347],
                                                                                                                ds12,
                                                                                                                ds4,
                                                                                                                result_8,
                                                                                                                ds6,
                                                                                                                c$ds_app_arg_0[314:314],
                                                                                                                c$ds_app_arg_0[313:304],
                                                                                                                {1'b1,
                                                                                                                 c$ds_app_arg_0[356:347],
                                                                                                                 ds12,
                                                                                                                 ds4,
                                                                                                                 result_8,
                                                                                                                 ds6,
                                                                                                                 c$ds_app_arg_0[314:314],
                                                                                                                 c$ds_app_arg_0[313:304]}};

  assign c$ds10_case_alt = c$ds_app_arg_0[303:303] ? {result_7,
                                                      c$ds10_case_alt_0,
                                                      c$ds_app_arg_0[292:289] == 4'b1000,
                                                      ds20_0[8:8],   ds20_0[7:0],   wild7,   brTg,
                                                      result_6 | (wild7 & (brTg != c$ds_app_arg_0[221:212]))} : {c$ds_app_arg_0[486:359],
                                                                                                                 c$ds_app_arg_0[496:487],
                                                                                                                 1'b0,
                                                                                                                 1'b0,
                                                                                                                 8'b00000000,
                                                                                                                 1'b0,
                                                                                                                 10'd0,
                                                                                                                 1'b0};

  assign result_selection_res = (\a#  == \b# ) ? 64'sd1 : 64'sd0;

  always @(*) begin
    case(result_selection_res)
      64'sd1 : result_6 = 1'b0;
      default : result_6 = 1'b1;
    endcase
  end

  assign c$dtt_rhs_3 = c$ds_app_arg_0[222:222];

  assign \b#  = $unsigned({{63 {1'b0}},
                           c$dtt_rhs_3});

  assign \a#  = $unsigned({{63 {1'b0}},   wild7});

  assign c$bv_3 = (((c$ds_app_arg_0[286:255])));

  assign ds20_0 = (c$ds_app_arg_0[292:289] == 4'b0111) ? {1'b1,
                                                          c$bv_3[7 : 0]} : {1'b0,   8'b00000000};

  assign c$ds10_case_alt_0 = wild7 ? brTg : c$ds_app_arg_0[496:487];

  assign brTg = ds19[9:0];

  assign wild7 = ds19[10:10];

  assign ds19 = (c$ds_app_arg_0[292:289] == 4'b1001) ? {1'b1,
                                                        c$ds19_case_alt_4} : c$ds19_case_alt_2;

  assign c$ds19_case_alt_2 = (c$ds_app_arg_0[292:289] == 4'b1010) ? {c$ds19_app_arg_0,
                                                                     c$ds19_app_arg} : c$ds19_case_alt_3;

  assign c$ds19_app_arg = c$ds19_app_arg_0 ? c$ds19_case_alt_4 : c$ds_app_arg_0[496:487];

  assign c$ds19_app_arg_0 = c$ds_app_arg_0[286:255] == 32'd0;

  assign c$ds19_case_alt_3 = (c$ds_app_arg_0[292:289] == 4'b1011) ? {c$ds19_app_arg_2,
                                                                     c$ds19_app_arg_1} : {1'b0,
                                                                                          c$ds_app_arg_0[496:487]};

  assign c$ds19_app_arg_1 = c$ds19_app_arg_2 ? c$ds19_case_alt_4 : c$ds_app_arg_0[496:487];

  assign c$bv_4 = c$ds_app_arg_0[254:223];

  assign c$ds19_case_alt_4 = c$bv_4[0+:10];

  assign c$ds19_app_arg_2 = c$ds_app_arg_0[286:255] != 32'd0;

  assign result_7 = c$ds10_case_scrut_3 ? c$ds10_case_alt_6 : c$ds10_case_alt_1;

  assign c$ds10_case_alt_1 = c$ds10_case_scrut_2 ? c$ds10_case_alt_6 : c$ds10_case_alt_2;

  assign c$ds10_case_alt_2 = c$ds10_case_scrut_1 ? c$ds10_case_alt_6 : c$ds10_case_alt_3;

  assign c$ds10_case_alt_3 = c$ds10_case_scrut_0 ? c$ds10_case_alt_6 : c$ds10_case_alt_4;

  assign c$ds10_case_alt_4 = c$ds10_case_scrut ? c$ds10_case_alt_6 : c$ds10_case_alt_5;

  assign c$ds10_case_alt_5 = (c$ds_app_arg_0[292:289] == 4'b0110) ? c$ds10_case_alt_6 : c$ds_app_arg_0[486:359];

  assign c$i_189 = c$ds_app_arg_0[288:287];

  assign c$vec_1 = c$ds_app_arg_0[486:359];

  // vector replace begin
  genvar i_3;
  generate
  for (i_3=0;i_3<4;i_3=i_3+1) begin : vector_replace_1
    assign c$ds10_case_alt_6[(3-i_3)*32+:32] = ($unsigned({{(64-2) {1'b0}},c$i_189})) == i_3 ? aluResult : c$vec_1[(3-i_3)*32+:32];
  end
  endgenerate
  // vector replace end

  assign aluResult = c$ds10_case_scrut_3 ? c$ds_app_arg_0[254:223] : c$aluResult_case_alt;

  assign c$aluResult_case_alt = c$ds10_case_scrut_2 ? (c$ds_app_arg_0[286:255] + c$ds_app_arg_0[254:223]) : c$aluResult_case_alt_0;

  assign c$aluResult_case_alt_0 = c$ds10_case_scrut_1 ? (c$ds_app_arg_0[286:255] - c$ds_app_arg_0[254:223]) : c$aluResult_case_alt_1;

  assign c$aluResult_case_alt_1 = c$ds10_case_scrut_0 ? (c$ds_app_arg_0[286:255] & c$ds_app_arg_0[254:223]) : c$aluResult_case_alt_2;

  assign c$aluResult_case_alt_2 = c$ds10_case_scrut ? (c$ds_app_arg_0[286:255] | c$ds_app_arg_0[254:223]) : c$ds_app_arg_0[286:255];

  assign c$ds10_case_scrut = c$ds_app_arg_0[292:289] == 4'b0101;

  assign c$ds10_case_scrut_0 = c$ds_app_arg_0[292:289] == 4'b0100;

  assign c$ds10_case_scrut_1 = c$ds_app_arg_0[292:289] == 4'b0011;

  assign c$ds10_case_scrut_2 = c$ds_app_arg_0[292:289] == 4'b0010;

  assign c$ds10_case_scrut_3 = c$ds_app_arg_0[292:289] == 4'b0001;

  assign ds12 = c$rsF_app_arg[31 : 28];

  assign c$bv_5 = ((c$rsF_app_arg[23 : 0]));

  assign ds6 = {{(32-24) {1'b0}},((c$rsF_app_arg[23 : 0]))};

  assign ds4 = (c$rsF_app_arg[27 : 26]);

  assign c$vecFlat = c$ds_app_arg_0[486:359];

  // index begin
  wire [31:0] vecArray_1 [0:4-1];
  genvar i_4;
  generate
  for (i_4=0; i_4 < 4; i_4=i_4+1) begin : mk_array_1
    assign vecArray_1[(4-1)-i_4] = c$vecFlat[i_4*32+:32];
  end
  endgenerate
  assign result_8 = vecArray_1[($unsigned({{(64-2) {1'b0}},rsF}))];
  // index end

  assign rsF = (c$rsF_app_arg[25 : 24]);

  assign c$rsF_app_arg = instr;

  assign instr = c$ds_app_arg_0[346:315];

  assign cpuEn = c$cpuEn_case_alt & (~ c$ds_app_arg_0[521:521]);

  always @(*) begin
    case(c$cpuEn_case_scrut)
      64'sd2 : c$cpuEn_case_alt = 1'b1;
      default : c$cpuEn_case_alt = 1'b0;
    endcase
  end

  assign c$cpuEn_case_scrut = $unsigned(eta1_0);

  assign rxVld = result_9[0:0];

  assign rxByte = result_9[8:1];

  assign \rx'  = result_9[41:9];

  assign result_9 = {{ds8[22:21],   ds8[20:12],
                      ds8[11:9],   \shift' ,   uart_rx_pin,
                      c$ds_app_arg_0[33:33],   c$dataOut_case_alt,
                      wild3},   {c$dataOut_case_alt,   wild3}};

  assign c$dataOut_case_alt = wild3 ? \shift'  : c$ds_app_arg_0[31:24];

  assign \shift'  = ds8[8:1];

  assign wild3 = ds8[0:0];

  assign ds8_selection_2 = c$ds_app_arg_0[55:54];

  always @(*) begin
    case(ds8_selection_2)
      2'b00 : ds8 = c$ds8_case_alt_2;
      2'b01 : ds8 = c$ds8_case_alt_1;
      2'b10 : ds8 = c$ds8_case_alt_0;
      default : ds8 = c$ds8_case_alt;
    endcase
  end

  assign c$ds8_case_alt = c$ds8_case_scrut ? {2'd0,
                                              9'd0,   3'd0,   c$ds_app_arg_0[41:34],
                                              c$ds_app_arg_0[32:32] == 1'b1} : {2'd3,
                                                                                c$ds8_app_arg,   c$ds_app_arg_0[44:42],
                                                                                c$ds_app_arg_0[41:34],   1'b0};

  assign c$ds8_case_alt_0 = c$ds8_case_scrut ? result_10 : {2'd2,
                                                            c$ds8_app_arg,   c$ds_app_arg_0[44:42],
                                                            c$ds_app_arg_0[41:34],   1'b0};

  assign c$ds8_case_alt_1 = (c$ds_app_arg_0[53:45] == 9'd116) ? c$ds8_case_alt_3 : {2'd1,
                                                                                    c$ds8_app_arg,
                                                                                    c$ds_app_arg_0[44:42],
                                                                                    c$ds_app_arg_0[41:34],   1'b0};

  assign c$ds8_case_alt_2 = c$ds8_case_scrut_0 ? {2'd1,
                                                  9'd0,   3'd0,   c$ds_app_arg_0[41:34],
                                                  1'b0} : {2'd0,   9'd0,   3'd0,
                                                           c$ds_app_arg_0[41:34],   1'b0};

  assign c$ds8_case_scrut = c$ds_app_arg_0[53:45] == 9'd233;

  assign result_10 = (c$ds_app_arg_0[44:42] == 3'd7) ? {2'd3,
                                                        9'd0,   c$ds_app_arg_0[44:42],   shifted,
                                                        1'b0} : {2'd2,   9'd0,
                                                                 c$ds_app_arg_0[44:42] + 3'd1,   shifted,
                                                                 1'b0};

  assign c$bv_6 = (c$ds_app_arg_0[41:34]);

  assign shifted = {((c$ds_app_arg_0[32:32])),(c$bv_6[7 : 1])};

  assign c$ds8_case_alt_3 = c$ds8_case_scrut_0 ? {2'd2,
                                                  9'd0,   3'd0,   c$ds_app_arg_0[41:34],
                                                  1'b0} : {2'd0,   9'd0,   3'd0,
                                                           c$ds_app_arg_0[41:34],   1'b0};

  assign c$ds8_app_arg = c$ds_app_arg_0[53:45] + 9'd1;

  assign c$ds8_case_scrut_0 = c$ds_app_arg_0[32:32] == 1'b0;

  assign result_11 = {{ds6_0[22:21],
                       ds6_0[20:12],   ds6_0[11:9],   ds6_0[8:1],
                       \pin' },   {\pin' ,   busy}};

  assign \pin'  = ds6_0[0:0];

  assign ds6_selection_2 = c$ds_app_arg_0[22:21];

  always @(*) begin
    case(ds6_selection_2)
      2'b00 : ds6_0 = c$ds6_case_alt_2;
      2'b01 : ds6_0 = c$ds6_case_alt_1;
      2'b10 : ds6_0 = c$ds6_case_alt_0;
      default : ds6_0 = c$ds6_case_alt;
    endcase
  end

  assign c$ds6_case_alt = c$ds6_case_scrut ? {2'd0,
                                              9'd0,   c$ds_app_arg_0[11:9],
                                              c$ds_app_arg_0[8:1],   1'b1} : {2'd3,
                                                                              c$ds6_app_arg_1,   c$ds_app_arg_0[11:9],
                                                                              c$ds_app_arg_0[8:1],   1'b1};

  assign c$ds6_case_alt_0 = c$ds6_case_scrut ? result_12 : {2'd2,
                                                            c$ds6_app_arg_1,   c$ds_app_arg_0[11:9],
                                                            c$ds_app_arg_0[8:1],   c$ds6_app_arg};

  assign c$ds6_case_alt_1 = c$ds6_case_scrut ? {2'd2,
                                                9'd0,   3'd0,   c$ds_app_arg_0[8:1],
                                                1'b0} : {2'd1,   c$ds6_app_arg_1,
                                                         c$ds_app_arg_0[11:9],   c$ds_app_arg_0[8:1],
                                                         1'b0};

  assign c$ds6_case_alt_2 = (send & (~ busy)) ? {2'd1,
                                                 9'd0,   3'd0,   dat,   1'b1} : {2'd0,
                                                                                 c$ds_app_arg_0[20:12],
                                                                                 c$ds_app_arg_0[11:9],
                                                                                 c$ds_app_arg_0[8:1],   1'b1};

  assign result_12 = (c$ds_app_arg_0[11:9] == 3'd7) ? {2'd3,
                                                       9'd0,   c$ds_app_arg_0[11:9],   shifted_0,
                                                       c$ds6_app_arg} : {2'd2,   9'd0,
                                                                         c$ds_app_arg_0[11:9] + 3'd1,   shifted_0,
                                                                         c$ds6_app_arg};

  assign shifted_0 = {1'b0,(c$ds6_app_arg_0[7 : 1])};

  assign c$ds6_app_arg =  c$ds6_app_arg_0[0] ;

  assign c$ds6_app_arg_0 = c$ds_app_arg_0[8:1];

  assign c$ds6_case_scrut = c$ds_app_arg_0[20:12] == 9'd233;

  assign c$ds6_app_arg_1 = c$ds_app_arg_0[20:12] + 9'd1;

  assign dat = ds7[8:1];

  assign send = ds7[0:0];

  always @(*) begin
    case(c$busy_case_scrut)
      64'sd0 : busy = 1'b0;
      default : busy = 1'b1;
    endcase
  end

  assign c$dtt_rhs_7 = c$ds_app_arg_0[22:21];

  assign c$busy_case_scrut = $unsigned(c$dtt_rhs_7);

  assign c$tupIn_0 = (c$ds_app_arg_0[521:521] & (~ ((fifo1[7:4] + 4'd1) == fifo1[3:0]))) ? {c$case_alt_16,
                                                                                            wild5,   {c$case_alt_16,
                                                                                                      wild5}} : {fifo1,
                                                                                                                 c$ds_app_arg_0[576:497],
                                                                                                                 {fifo1,
                                                                                                                  c$ds_app_arg_0[576:497]}};

  assign wild5 = {eta1_0,   progByteIdx1_1,
                  progWordAcc1_1,   cpu3Rst1_1,   led3Latch1_0,
                  1'b0,   out3PendDat1_1,   runTimeout1_0};

  assign runTimeout1_0 = c$ds_app_arg_0[512:497];

  assign led3Latch1_0 = c$ds_app_arg_0[529:522];

  assign cpu3Rst1_1 = c$ds_app_arg_0[530:530];

  assign progWordAcc1_1 = c$ds_app_arg_0[562:531];

  assign progByteIdx1_1 = c$ds_app_arg_0[574:563];

  assign eta1_0 = c$ds_app_arg_0[576:575];

  assign c$case_alt_16 = {c$app_arg_6,
                          fifo1[7:4] + 4'd1,   fifo1[3:0]};

  assign c$i_242 = fifo1[7:4];

  assign c$vec_2 = fifo1[135:8];

  // vector replace begin
  genvar i_5;
  generate
  for (i_5=0;i_5<16;i_5=i_5+1) begin : vector_replace_2
    assign c$app_arg_6[(15-i_5)*8+:8] = ($unsigned({{(64-4) {1'b0}},c$i_242})) == i_5 ? out3PendDat1_1 : c$vec_2[(15-i_5)*8+:8];
  end
  endgenerate
  // vector replace end

  assign fifo1 = ds7[144:9];

  assign ds7 = ((~ (c$ds_app_arg_0[63:60] == c$ds_app_arg_0[59:56])) & (~ c$ds7_case_alt)) ? {c$case_alt_17[143:8],
                                                                                              c$case_alt_17[7:0],
                                                                                              1'b1} : {c$ds_app_arg_0[191:56],
                                                                                                       8'b00000000,
                                                                                                       1'b0};

  always @(*) begin
    case(c$ds7_case_scrut)
      64'sd0 : c$ds7_case_alt = 1'b0;
      default : c$ds7_case_alt = 1'b1;
    endcase
  end

  assign c$dtt_rhs_11 = c$ds_app_arg_0[22:21];

  assign c$ds7_case_scrut = $unsigned(c$dtt_rhs_11);

  assign c$case_alt_17 = {{c$ds_app_arg_0[191:64],
                           c$ds_app_arg_0[63:60],
                           c$ds_app_arg_0[59:56] + 4'd1},   c$app_arg_7};

  assign c$i_245 = c$ds_app_arg_0[59:56];

  assign c$vecFlat_0 = c$ds_app_arg_0[191:64];

  // index begin
  wire [7:0] vecArray_2 [0:16-1];
  genvar i_6;
  generate
  for (i_6=0; i_6 < 16; i_6=i_6+1) begin : mk_array_2
    assign vecArray_2[(16-1)-i_6] = c$vecFlat_0[i_6*8+:8];
  end
  endgenerate
  assign c$app_arg_7 = vecArray_2[($unsigned({{(64-4) {1'b0}},c$i_245}))];
  // index end

  assign out3PendDat1_1 = c$ds_app_arg_0[520:513];

  assign eta3 = fullOut[42:0];

  assign ds1 = eta3[42:42] ? a1 : {{10 {1'bx}},
                                   32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};

  assign uart_tx_pin = result[6:6];

  assign led = result[5:0];


endmodule

